server.port=${BAYKUL_SERVER_PORT:8080}
spring.application.name=Baykul Web Application

spring.datasource.url=${BAYKUL_DATABASE_URL:jdbc:postgresql://localhost:5432/baykul}
spring.datasource.username=${BAYKUL_DATABASE_USER:baykul_user}
spring.datasource.password=${BAYKUL_DATABASE_PASSWORD:baykul_pass}

spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
# NOTE: Be sure to replace with validate
spring.jpa.hibernate.ddl-auto=create

jwt.secret.access=${JWT_SECRET:FyGgATxvUgvZNgVvpIqsDvDxuhyHQTxVkBMoP1kXnCke1HJzz2Q70Uavl4tsejgBBzWsuIrIzXVpiWFKNQY+Ng==}
jwt.secret.refresh=${JWT_REFRESH_SECRET:vhvyF6Xx10wco5htwza5AU8NjH4lpTG5Q6zdLz4tpCUSJtHKnFvmoroCct3SxmQ5BtIlf7HDYDfuW6wB3bSecw==}

logging.file.name=log/baykul-application.log
spring.main.banner-mode=off
logging.logback.rollingpolicy.clean-history-on-start=true
logging.pattern.console=